# Generated by Django 6.1 on 2026-08-16 00:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qty', models.PositiveIntegerField()),
                ('unit_price_cents_snapshot', models.PositiveIntegerField()),
                ('product_name_snapshot', models.TextField()),
                ('image_key_snapshot', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='events.event')),
                ('variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='catalog.variant')),
            ],
            options={
                'db_table': 'events_order_line',
                'ordering': ['created_at'],
            },
        ),
    ]
