# Generated by Django 6.1 on 2026-08-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('ordered', 'Ordered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
