# Generated by Django 6.0.6 on 2026-08-01 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_tenant_options'),
        ('users', '0003_legalrepresentative_user_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='document_id_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='legal_representative',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant', to='users.legalrepresentative'),
        ),
    ]
