# Generated by Django 6.1 on 2026-08-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_document_id_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='order_notification_emails',
            field=models.JSONField(blank=True, db_default=[], default=list),
        ),
    ]
