# Generated by Django 5.0.10 on 2026-07-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("Master", "Master"), ("Operator", "Operator")],
                default="Operator",
                max_length=50,
            ),
        ),
    ]
